# Nuclear Migration Fix - Downgrade and Resync Strategy
# This approach downgrades to last known good state, then rebuilds

Write-Host "Starting nuclear migration fix..." -ForegroundColor Cyan
Write-Host "This will downgrade to a stable state and rebuild" -ForegroundColor Yellow
Write-Host ""

# Activate virtual environment
& .venv\Scripts\Activate.ps1

# Step 1: Get last stable migration
Write-Host "Downgrading to last stable migration (48cc745d4daa)..." -ForegroundColor Yellow
alembic downgrade 48cc745d4daa
if ($LASTEXITCODE -eq 0) {
    Write-Host "Successfully downgraded to stable state." -ForegroundColor Green
} else {
    Write-Host "Could not downgrade. Checking current state..." -ForegroundColor Yellow
}
Write-Host ""

# Step 2: Mark all problematic migrations as complete using stamp
Write-Host "Marking all migrations as complete..." -ForegroundColor Yellow
alembic stamp head
Write-Host "OK - Stamped to head" -ForegroundColor Green
Write-Host ""

# Step 3: Now autogenerate for any schema changes
Write-Host "Autogenerating migration for current schema differences..." -ForegroundColor Yellow
alembic revision --autogenerate -m "sync_all_schema_changes"
if ($LASTEXITCODE -eq 0) {
    Write-Host "Successfully generated migration file." -ForegroundColor Green
    Write-Host ""
    Write-Host "CHECK the generated migration file and review it!" -ForegroundColor Cyan
    Write-Host "Location: alembic/versions/" -ForegroundColor Cyan
    Write-Host ""
    
    # Step 4: Apply it
    Write-Host "Applying autogenerated migration..." -ForegroundColor Yellow
    alembic upgrade head
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Successfully applied all schema changes!" -ForegroundColor Green
    } else {
        Write-Host "Error applying migration. Manual review needed." -ForegroundColor Red
    }
} else {
    Write-Host "Error: Could not autogenerate migration." -ForegroundColor Red
    Write-Host "Check ORM models for syntax errors" -ForegroundColor Red
    exit 1
}
Write-Host ""

# Step 5: Final verification
Write-Host "Final migration status:" -ForegroundColor Yellow
alembic current
Write-Host ""
Write-Host "Migration fix complete!" -ForegroundColor Green
