"""add_batches_and_serial_numbers_tables

Revision ID: 04a72257dad8
Revises: 8ce8b1193823
Create Date: 2026-03-24 17:28:30.437048

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a72257dad8'
down_revision = '8ce8b1193823'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'material_id', 'batch_number', name='uq_batch_tenant_material_number')
    )
    op.create_index('ix_batches_expiry_date', 'batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_batches_material_id'), 'batches', ['material_id'], unique=False)
    op.create_index('ix_batches_tenant_batch_number', 'batches', ['tenant_id', 'batch_number'], unique=False)
    op.create_index('ix_batches_tenant_id', 'batches', ['tenant_id'], unique=False)
    op.create_index('ix_batches_tenant_material', 'batches', ['tenant_id', 'material_id'], unique=False)
    op.create_table('serial_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_location_id', sa.UUID(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'serial_number', name='uq_serial_tenant_serial_number')
    )
    op.create_index(op.f('ix_serial_numbers_material_id'), 'serial_numbers', ['material_id'], unique=False)
    op.create_index('ix_serial_numbers_status', 'serial_numbers', ['status'], unique=False)
    op.create_index('ix_serial_numbers_tenant_id', 'serial_numbers', ['tenant_id'], unique=False)
    op.create_index('ix_serial_numbers_tenant_serial', 'serial_numbers', ['tenant_id', 'serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_serial_numbers_tenant_serial', table_name='serial_numbers')
    op.drop_index('ix_serial_numbers_tenant_id', table_name='serial_numbers')
    op.drop_index('ix_serial_numbers_status', table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_material_id'), table_name='serial_numbers')
    op.drop_table('serial_numbers')
    op.drop_index('ix_batches_tenant_material', table_name='batches')
    op.drop_index('ix_batches_tenant_id', table_name='batches')
    op.drop_index('ix_batches_tenant_batch_number', table_name='batches')
    op.drop_index(op.f('ix_batches_material_id'), table_name='batches')
    op.drop_index('ix_batches_expiry_date', table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
