"""Add simple Phase 2.2 BOM tables

Revision ID: 1d1a41830cdd
Revises: 7a79a6e7f554
Create Date: 2026-03-24 23:15:21.559284

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1a41830cdd'
down_revision = '7a79a6e7f554'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(template_id IS NOT NULL AND variant_id IS NULL) OR (template_id IS NULL AND variant_id IS NOT NULL)', name='chk_bom_product_target'),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['item_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'template_id', 'version', name='uq_bom_tenant_template_version'),
    sa.UniqueConstraint('tenant_id', 'variant_id', 'version', name='uq_bom_tenant_variant_version')
    )
    op.create_index('ix_bom_tenant_product', 'boms', ['tenant_id', 'template_id', 'variant_id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bom_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('scrap_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(CASE WHEN material_id IS NULL THEN 0 ELSE 1 END + CASE WHEN template_id IS NULL THEN 0 ELSE 1 END + CASE WHEN variant_id IS NULL THEN 0 ELSE 1 END) = 1', name='chk_bom_line_component'),
    sa.CheckConstraint('quantity > 0', name='chk_bom_line_qty_positive'),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units_of_measure.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['item_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bom_line_tenant_bom', 'bom_lines', ['tenant_id', 'bom_id'], unique=False)
    op.create_index(op.f('ix_bom_lines_bom_id'), 'bom_lines', ['bom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_lines_bom_id'), table_name='bom_lines')
    op.drop_index('ix_bom_line_tenant_bom', table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index('ix_bom_tenant_product', table_name='boms')
    op.drop_table('boms')
    # ### end Alembic commands ###
