"""sync_all_schema_changes

Revision ID: a62c0f8c9545
Revises: raw_material_onboarding
Create Date: 2026-05-27 19:34:13.624298

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62c0f8c9545'
down_revision = 'raw_material_onboarding'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_import_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_import_mappings_tenant_id'), 'material_import_mappings', ['tenant_id'], unique=False)
    op.create_table('material_onboarding_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('defaults_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_onboarding_profiles_tenant_id'), 'material_onboarding_profiles', ['tenant_id'], unique=False)
    op.create_table('material_onboarding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('protected_changes_confirmed', sa.Boolean(), nullable=False),
    sa.Column('original_headers_json', sa.Text(), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_onboarding_sessions_tenant_id'), 'material_onboarding_sessions', ['tenant_id'], unique=False)
    op.create_table('material_onboarding_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('normalized_json', sa.Text(), nullable=False),
    sa.Column('validation_json', sa.Text(), nullable=False),
    sa.Column('protected_changes_json', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('result_material_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['material_onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_onboarding_rows_session_id'), 'material_onboarding_rows', ['session_id'], unique=False)
    op.create_index(op.f('ix_material_onboarding_rows_tenant_id'), 'material_onboarding_rows', ['tenant_id'], unique=False)
    op.drop_index('ix_rfq_supplier_rfq', table_name='rfq_suppliers')
    op.drop_table('rfq_suppliers')
    op.drop_table('subcontract_number_sequences')
    op.drop_index('ix_tenant_roles_name', table_name='tenant_roles')
    op.drop_index('ix_tenant_roles_tenant_id', table_name='tenant_roles')
    op.drop_table('tenant_roles')
    op.drop_index('ix_delivery_lines_delivery', table_name='delivery_lines')
    op.drop_index('ix_delivery_lines_sales_line', table_name='delivery_lines')
    op.drop_table('delivery_lines')
    op.drop_index('ix_rfq_lines_rfq', table_name='rfq_lines')
    op.drop_table('rfq_lines')
    op.drop_index('ix_tenant_role_permissions_permission', table_name='tenant_role_permissions')
    op.drop_index('ix_tenant_role_permissions_role_id', table_name='tenant_role_permissions')
    op.drop_table('tenant_role_permissions')
    op.drop_index('ix_invoice_dispute_invoice', table_name='invoice_disputes')
    op.drop_table('invoice_disputes')
    op.drop_index('ix_rfq_tenant', table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index('ix_stock_levels_loc', table_name='stock_levels')
    op.drop_index('ix_stock_levels_tenant_mat', table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index('ix_qr_ncr', table_name='quarantine_releases')
    op.drop_table('quarantine_releases')
    op.drop_table('rfq_number_sequences')
    op.drop_index('ix_delivery_orders_sales_order', table_name='delivery_orders')
    op.drop_index('ix_delivery_orders_tenant_status', table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.add_column('batches', sa.Column('original_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('batches', sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('batches', sa.Column('consumed_quantity', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('batches', sa.Column('returned_quantity', sa.Numeric(precision=18, scale=4), nullable=False))
    op.alter_column('error_logs', 'query_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('error_logs', 'headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_insp_det_inspection', table_name='inspection_details')
    op.drop_index('ix_insp_tpl_tenant', table_name='inspection_templates')
    op.add_column('inventory_transactions', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'inventory_transactions', 'batches', ['batch_id'], ['id'])
    op.create_index(op.f('ix_item_code_sequences_tenant_id'), 'item_code_sequences', ['tenant_id'], unique=False)
    op.drop_index('ix_item_variants_material_id', table_name='item_variants')
    op.add_column('job_cards', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_cards', sa.Column('total_downtime_seconds', sa.Numeric(precision=15, scale=3), nullable=False))
    op.add_column('job_cards', sa.Column('pause_reason', sa.String(length=255), nullable=True))
    op.add_column('job_cards', sa.Column('operator_notes', sa.Text(), nullable=True))
    op.add_column('job_cards', sa.Column('produced_quantity', sa.Numeric(precision=15, scale=3), nullable=False))
    op.add_column('job_cards', sa.Column('scrap_quantity', sa.Numeric(precision=15, scale=3), nullable=False))
    op.add_column('job_cards', sa.Column('rework_quantity', sa.Numeric(precision=15, scale=3), nullable=False))
    op.add_column('job_cards', sa.Column('rejected_quantity', sa.Numeric(precision=15, scale=3), nullable=False))
    op.drop_index('uq_locations_tenant_code', table_name='locations', postgresql_where='((code IS NOT NULL) AND (is_deleted = false))')
    op.alter_column('material_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('materials', sa.Column('length_uom', sa.String(length=20), nullable=True))
    op.add_column('materials', sa.Column('length_per_unit', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('materials', sa.Column('weight_per_unit', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('materials', sa.Column('dimension_spec', sa.String(), nullable=True))
    op.add_column('materials', sa.Column('preferred_supplier_id', sa.UUID(), nullable=True))
    op.add_column('materials', sa.Column('hazardous_flag', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('qc_required_flag', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('barcode', sa.String(length=120), nullable=True))
    op.add_column('materials', sa.Column('traceability_enabled', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('batch_rule', sa.String(length=20), nullable=True))
    op.add_column('materials', sa.Column('expiry_tracking', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('shelf_life_days', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('quarantine_required', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('cuttable_inventory', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('remaining_quantity_tracking', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('reusable_remainder', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('decimal_precision', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('supplier_item_code', sa.String(length=120), nullable=True))
    op.add_column('materials', sa.Column('purchase_uom', sa.String(length=40), nullable=True))
    op.add_column('materials', sa.Column('min_stock', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('materials', sa.Column('max_stock', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('materials', sa.Column('reorder_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('materials', sa.Column('moq', sa.Numeric(precision=18, scale=4), nullable=True))
    op.create_foreign_key(None, 'materials', 'suppliers', ['preferred_supplier_id'], ['id'])
    op.create_index(op.f('ix_mrp_suggestions_tenant_id'), 'mrp_suggestions', ['tenant_id'], unique=False)
    op.drop_index('ix_ncr_tenant', table_name='non_conformance_reports')
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'email_sent')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'email_sent_at')
    op.drop_index('ix_pol_material', table_name='purchase_order_lines')
    op.drop_index('ix_pol_po', table_name='purchase_order_lines')
    op.drop_index('ix_po_status', table_name='purchase_orders')
    op.drop_constraint('uq_po_tenant_number', 'purchase_orders', type_='unique')
    op.drop_index('ix_sales_order_lines_work_order_id', table_name='sales_order_lines')
    op.drop_index('ix_sales_orders_approver_id', table_name='sales_orders')
    op.drop_index('ix_sales_orders_pending_approval', table_name='sales_orders', postgresql_where='(is_deleted = false)')
    op.drop_index('ix_smi_order', table_name='subcontract_material_issues')
    op.drop_index('ix_sph_material', table_name='supplier_price_history')
    op.drop_index('ix_sph_supplier', table_name='supplier_price_history')
    op.drop_column('supplier_price_history', 'effective_to')
    op.drop_index('ix_sq_status', table_name='supplier_quotations')
    op.drop_constraint('supplier_quotations_rfq_id_fkey', 'supplier_quotations', type_='foreignkey')
    op.drop_column('supplier_quotations', 'rfq_id')
    op.drop_index('ix_suppliers_active', table_name='suppliers', postgresql_where='(is_deleted = false)')
    op.alter_column('units_of_measure', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_users_supplier', table_name='users', postgresql_where='(supplier_id IS NOT NULL)')
    op.create_index(op.f('ix_users_supplier_id'), 'users', ['supplier_id'], unique=False)
    op.drop_index('ix_wo_materials_work_order_id', table_name='work_order_materials')
    op.alter_column('work_orders', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'RELEASED', 'IN_PROGRESS', 'COMPLETED', 'CLOSED', name='work_order_status', metadata=MetaData()),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_index('ix_work_orders_sales_order_id', table_name='work_orders')
    op.drop_index('ix_work_orders_sales_order_line_id', table_name='work_orders')
    op.drop_constraint('work_orders_sales_order_line_id_fkey', 'work_orders', type_='foreignkey')
    op.drop_constraint('uix_workstation_tenant_code', 'workstations', type_='unique')
    op.create_index(op.f('ix_workstations_code'), 'workstations', ['code'], unique=False)
    op.create_unique_constraint('uq_workstation_tenant_code', 'workstations', ['tenant_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workstation_tenant_code', 'workstations', type_='unique')
    op.drop_index(op.f('ix_workstations_code'), table_name='workstations')
    op.create_unique_constraint('uix_workstation_tenant_code', 'workstations', ['tenant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key('work_orders_sales_order_line_id_fkey', 'work_orders', 'sales_order_lines', ['sales_order_line_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_work_orders_sales_order_line_id', 'work_orders', ['sales_order_line_id'], unique=False)
    op.create_index('ix_work_orders_sales_order_id', 'work_orders', ['sales_order_id'], unique=False)
    op.alter_column('work_orders', 'status',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('PLANNED', 'RELEASED', 'IN_PROGRESS', 'COMPLETED', 'CLOSED', name='work_order_status', metadata=MetaData()),
               existing_nullable=False)
    op.create_index('ix_wo_materials_work_order_id', 'work_order_materials', ['work_order_id'], unique=False)
    op.drop_index(op.f('ix_users_supplier_id'), table_name='users')
    op.create_index('ix_users_supplier', 'users', ['supplier_id'], unique=False, postgresql_where='(supplier_id IS NOT NULL)')
    op.alter_column('units_of_measure', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_suppliers_active', 'suppliers', ['tenant_id', 'is_active'], unique=False, postgresql_where='(is_deleted = false)')
    op.add_column('supplier_quotations', sa.Column('rfq_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('supplier_quotations_rfq_id_fkey', 'supplier_quotations', 'rfqs', ['rfq_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_sq_status', 'supplier_quotations', ['status'], unique=False)
    op.add_column('supplier_price_history', sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_sph_supplier', 'supplier_price_history', ['supplier_id'], unique=False)
    op.create_index('ix_sph_material', 'supplier_price_history', ['material_id'], unique=False)
    op.create_index('ix_smi_order', 'subcontract_material_issues', ['subcontract_order_id'], unique=False)
    op.create_index('ix_sales_orders_pending_approval', 'sales_orders', ['tenant_id', 'status', 'approver_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('ix_sales_orders_approver_id', 'sales_orders', ['approver_id'], unique=False)
    op.create_index('ix_sales_order_lines_work_order_id', 'sales_order_lines', ['work_order_id'], unique=False)
    op.create_unique_constraint('uq_po_tenant_number', 'purchase_orders', ['tenant_id', 'po_number'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_po_status', 'purchase_orders', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_pol_po', 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_index('ix_pol_material', 'purchase_order_lines', ['material_id'], unique=False)
    op.add_column('notifications', sa.Column('email_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('email_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'notification_type')
    op.create_index('ix_ncr_tenant', 'non_conformance_reports', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_mrp_suggestions_tenant_id'), table_name='mrp_suggestions')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'moq')
    op.drop_column('materials', 'reorder_quantity')
    op.drop_column('materials', 'max_stock')
    op.drop_column('materials', 'min_stock')
    op.drop_column('materials', 'purchase_uom')
    op.drop_column('materials', 'supplier_item_code')
    op.drop_column('materials', 'decimal_precision')
    op.drop_column('materials', 'reusable_remainder')
    op.drop_column('materials', 'remaining_quantity_tracking')
    op.drop_column('materials', 'cuttable_inventory')
    op.drop_column('materials', 'quarantine_required')
    op.drop_column('materials', 'shelf_life_days')
    op.drop_column('materials', 'expiry_tracking')
    op.drop_column('materials', 'batch_rule')
    op.drop_column('materials', 'traceability_enabled')
    op.drop_column('materials', 'barcode')
    op.drop_column('materials', 'qc_required_flag')
    op.drop_column('materials', 'hazardous_flag')
    op.drop_column('materials', 'preferred_supplier_id')
    op.drop_column('materials', 'dimension_spec')
    op.drop_column('materials', 'weight_per_unit')
    op.drop_column('materials', 'length_per_unit')
    op.drop_column('materials', 'length_uom')
    op.alter_column('material_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('uq_locations_tenant_code', 'locations', ['tenant_id', 'code'], unique=True, postgresql_where='((code IS NOT NULL) AND (is_deleted = false))')
    op.drop_column('job_cards', 'rejected_quantity')
    op.drop_column('job_cards', 'rework_quantity')
    op.drop_column('job_cards', 'scrap_quantity')
    op.drop_column('job_cards', 'produced_quantity')
    op.drop_column('job_cards', 'operator_notes')
    op.drop_column('job_cards', 'pause_reason')
    op.drop_column('job_cards', 'total_downtime_seconds')
    op.drop_column('job_cards', 'paused_at')
    op.create_index('ix_item_variants_material_id', 'item_variants', ['material_id'], unique=False)
    op.drop_index(op.f('ix_item_code_sequences_tenant_id'), table_name='item_code_sequences')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'batch_id')
    op.create_index('ix_insp_tpl_tenant', 'inspection_templates', ['tenant_id'], unique=False)
    op.create_index('ix_insp_det_inspection', 'inspection_details', ['inspection_id'], unique=False)
    op.alter_column('error_logs', 'headers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('error_logs', 'query_params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('batches', 'returned_quantity')
    op.drop_column('batches', 'consumed_quantity')
    op.drop_column('batches', 'reserved_quantity')
    op.drop_column('batches', 'original_quantity')
    op.create_table('delivery_orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('delivery_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sales_order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('carrier', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('shipped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['DRAFT'::character varying, 'PACKING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying]::text[])", name='ck_delivery_order_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='delivery_orders_created_by_fkey'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name='delivery_orders_sales_order_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='delivery_orders_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='delivery_orders_pkey'),
    sa.UniqueConstraint('tenant_id', 'delivery_number', name='uq_delivery_order_tenant_number', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_delivery_orders_tenant_status', 'delivery_orders', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_delivery_orders_sales_order', 'delivery_orders', ['sales_order_id'], unique=False)
    op.create_table('rfq_number_sequences',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='rfq_number_sequences_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', name='rfq_number_sequences_pkey')
    )
    op.create_table('quarantine_releases',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ncr_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('released_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('released_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('new_location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ncr_id'], ['non_conformance_reports.id'], name='quarantine_releases_ncr_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_location_id'], ['locations.id'], name='quarantine_releases_new_location_id_fkey'),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name='quarantine_releases_released_by_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='quarantine_releases_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quarantine_releases_pkey')
    )
    op.create_index('ix_qr_ncr', 'quarantine_releases', ['ncr_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("stock_status::text = ANY (ARRAY['available'::character varying, 'pending_inspection'::character varying, 'quarantine'::character varying]::text[])", name='stock_levels_stock_status_check'),
    sa.CheckConstraint('quantity >= 0::numeric', name='stock_levels_quantity_check'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='stock_levels_location_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='stock_levels_material_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='stock_levels_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_levels_pkey'),
    sa.UniqueConstraint('tenant_id', 'material_id', 'location_id', 'stock_status', name='uq_stock_levels_bucket', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_stock_levels_tenant_mat', 'stock_levels', ['tenant_id', 'material_id'], unique=False)
    op.create_index('ix_stock_levels_loc', 'stock_levels', ['location_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rfq_number', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('material_request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('awarded_supplier_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('awarded_po_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['awarded_po_id'], ['purchase_orders.id'], name='rfqs_awarded_po_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['awarded_supplier_id'], ['suppliers.id'], name='rfqs_awarded_supplier_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='rfqs_created_by_fkey'),
    sa.ForeignKeyConstraint(['material_request_id'], ['material_requests.id'], name='rfqs_material_request_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='rfqs_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rfqs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_rfq_tenant', 'rfqs', ['tenant_id'], unique=False)
    op.create_table('invoice_disputes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('disputed_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raised_by_supplier', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name='invoice_disputes_resolved_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], name='invoice_disputes_supplier_invoice_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='invoice_disputes_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='invoice_disputes_pkey')
    )
    op.create_index('ix_invoice_dispute_invoice', 'invoice_disputes', ['supplier_invoice_id'], unique=False)
    op.create_table('tenant_role_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tenant_roles.id'], name='tenant_role_permissions_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tenant_role_permissions_pkey'),
    sa.UniqueConstraint('role_id', 'permission', name='uq_tenant_role_permission', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_tenant_role_permissions_role_id', 'tenant_role_permissions', ['role_id'], unique=False)
    op.create_index('ix_tenant_role_permissions_permission', 'tenant_role_permissions', ['permission'], unique=False)
    op.create_table('rfq_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rfq_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='rfq_lines_material_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name='rfq_lines_rfq_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='rfq_lines_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rfq_lines_pkey')
    )
    op.create_index('ix_rfq_lines_rfq', 'rfq_lines', ['rfq_id'], unique=False)
    op.create_table('delivery_lines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('delivery_order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sales_order_line_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity > 0::numeric', name='delivery_lines_quantity_check'),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], name='delivery_lines_delivery_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], name='delivery_lines_sales_order_line_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='delivery_lines_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='delivery_lines_pkey')
    )
    op.create_index('ix_delivery_lines_sales_line', 'delivery_lines', ['sales_order_line_id'], unique=False)
    op.create_index('ix_delivery_lines_delivery', 'delivery_lines', ['delivery_order_id'], unique=False)
    op.create_table('tenant_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='tenant_roles_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tenant_roles_pkey'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_role_name', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_tenant_roles_tenant_id', 'tenant_roles', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_roles_name', 'tenant_roles', ['name'], unique=False)
    op.create_table('subcontract_number_sequences',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='subcontract_number_sequences_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', name='subcontract_number_sequences_pkey')
    )
    op.create_table('rfq_suppliers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rfq_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'invited'::character varying"), autoincrement=False, nullable=False),
    sa.Column('quotation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['supplier_quotations.id'], name='rfq_suppliers_quotation_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name='rfq_suppliers_rfq_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='rfq_suppliers_supplier_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='rfq_suppliers_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rfq_suppliers_pkey')
    )
    op.create_index('ix_rfq_supplier_rfq', 'rfq_suppliers', ['rfq_id', 'supplier_id'], unique=False)
    op.drop_index(op.f('ix_material_onboarding_rows_tenant_id'), table_name='material_onboarding_rows')
    op.drop_index(op.f('ix_material_onboarding_rows_session_id'), table_name='material_onboarding_rows')
    op.drop_table('material_onboarding_rows')
    op.drop_index(op.f('ix_material_onboarding_sessions_tenant_id'), table_name='material_onboarding_sessions')
    op.drop_table('material_onboarding_sessions')
    op.drop_index(op.f('ix_material_onboarding_profiles_tenant_id'), table_name='material_onboarding_profiles')
    op.drop_table('material_onboarding_profiles')
    op.drop_index(op.f('ix_material_import_mappings_tenant_id'), table_name='material_import_mappings')
    op.drop_table('material_import_mappings')
    # ### end Alembic commands ###
