"""add_2fa_to_users_and_create_user_devices

Revision ID: 2fa_add_auth_enhancements
Revises: 62476545ff2f
Create Date: 2026-04-14 12:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2fa_add_auth_enhancements'
down_revision = '62476545ff2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add 2FA columns to users table
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    
    # Create user_devices table for device trust
    op.create_table(
        'user_devices',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
        sa.Column('device_name', sa.String(length=255), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('trusted_until', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indices on user_devices
    op.create_index('ix_user_devices_user', 'user_devices', ['user_id'])
    op.create_index('ix_user_devices_tenant', 'user_devices', ['tenant_id'])
    op.create_unique_constraint('uq_user_device_fingerprint', 'user_devices', ['user_id', 'device_fingerprint'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop user_devices table
    op.drop_constraint('uq_user_device_fingerprint', 'user_devices', type_='unique')
    op.drop_index('ix_user_devices_tenant', table_name='user_devices')
    op.drop_index('ix_user_devices_user', table_name='user_devices')
    op.drop_table('user_devices')
    
    # Remove 2FA columns from users table
    op.drop_column('users', 'backup_codes')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    
    # ### end Alembic commands ###
