"""phase1_safe_schema_sync_batch_location_fields

Revision ID: 466af3c8b765
Revises: 04a72257dad8
Create Date: 2026-03-24 17:55:12.306003

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466af3c8b765'
down_revision = '04a72257dad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('remaining_quantity', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('batches', sa.Column('location_id', sa.UUID(), nullable=True))
    op.add_column('batches', sa.Column('status', sa.String(length=20), server_default='in_stock', nullable=False))
    op.create_foreign_key(None, 'batches', 'locations', ['location_id'], ['id'])
    op.alter_column('locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.create_index('ix_location_tenant_id', 'locations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_tenant_id', table_name='locations')
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.alter_column('locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'status')
    op.drop_column('batches', 'location_id')
    op.drop_column('batches', 'remaining_quantity')
    # ### end Alembic commands ###
