"""Add inventory management enhancements

Revision ID: 48cc745d4daa
Revises: 5220b176bbc6
Create Date: 2026-04-15 00:28:37.952415

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48cc745d4daa'
down_revision = '5220b176bbc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_location_id', sa.UUID(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wh_zone_tenant_location', 'warehouse_zones', ['tenant_id', 'warehouse_location_id'], unique=False)
    op.create_table('stock_ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_tenant_date', 'stock_ledger_entries', ['tenant_id', 'transaction_date'], unique=False)
    op.create_index('ix_ledger_tenant_material', 'stock_ledger_entries', ['tenant_id', 'material_id'], unique=False)
    op.create_table('stock_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_res_tenant_mat', 'stock_reservations', ['tenant_id', 'material_id'], unique=False)
    op.create_index('ix_stock_res_tenant_status', 'stock_reservations', ['tenant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_stock_res_tenant_status', table_name='stock_reservations')
    op.drop_index('ix_stock_res_tenant_mat', table_name='stock_reservations')
    op.drop_table('stock_reservations')
    op.drop_index('ix_ledger_tenant_material', table_name='stock_ledger_entries')
    op.drop_index('ix_ledger_tenant_date', table_name='stock_ledger_entries')
    op.drop_table('stock_ledger_entries')
    op.drop_index('ix_wh_zone_tenant_location', table_name='warehouse_zones')
    op.drop_table('warehouse_zones')
    # ### end Alembic commands ###
