"""add_currency_to_tenants

Revision ID: 62476545ff2f
Revises: 26_make_unit_id_nullable
Create Date: 2026-03-26 19:06:17.252900

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62476545ff2f'
down_revision = '26_make_unit_id_nullable'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('currency_code', sa.String(length=10), nullable=True))
    op.add_column('tenants', sa.Column('currency_symbol', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'currency_symbol')
    op.drop_column('tenants', 'currency_code')
    # ### end Alembic commands ###
