"""Add precision to units_of_measure

Revision ID: 68c163da4d5a
Revises: d332efdcc036
Create Date: 2026-03-24 16:47:35.602888

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c163da4d5a'
down_revision = 'd332efdcc036'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units_of_measure', sa.Column('precision', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units_of_measure', 'precision')
    # ### end Alembic commands ###
