"""add_item_templates_and_item_variants

Revision ID: 7a79a6e7f554
Revises: 466af3c8b765
Create Date: 2026-03-24 20:03:50.887638

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a79a6e7f554'
down_revision = '466af3c8b765'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('base_unit_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_item_template_tenant_code')
    )
    op.create_index('ix_item_templates_tenant_code', 'item_templates', ['tenant_id', 'code'], unique=False)
    op.create_index('ix_item_templates_tenant_id', 'item_templates', ['tenant_id'], unique=False)
    op.create_table('item_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('variant_key', sa.String(length=500), nullable=False),
    sa.Column('attribute_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_unit_id', sa.UUID(), nullable=True),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_item_variant_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'template_id', 'variant_key', name='uq_item_variant_key')
    )
    op.create_index('ix_item_variants_template_id', 'item_variants', ['template_id'], unique=False)
    op.create_index('ix_item_variants_tenant_id', 'item_variants', ['tenant_id'], unique=False)
    op.create_index('ix_item_variants_variant_key', 'item_variants', ['tenant_id', 'template_id', 'variant_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_variants_variant_key', table_name='item_variants')
    op.drop_index('ix_item_variants_tenant_id', table_name='item_variants')
    op.drop_index('ix_item_variants_template_id', table_name='item_variants')
    op.drop_table('item_variants')
    op.drop_index('ix_item_templates_tenant_id', table_name='item_templates')
    op.drop_index('ix_item_templates_tenant_code', table_name='item_templates')
    op.drop_table('item_templates')
    # ### end Alembic commands ###
