"""Add stock and tracking columns to materials

Revision ID: 8ce8b1193823
Revises: 68c163da4d5a
Create Date: 2026-03-24 17:01:23.007403

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce8b1193823'
down_revision = '68c163da4d5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('current_stock', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('materials', sa.Column('reserved_stock', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('materials', sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('materials', sa.Column('location_id', sa.UUID(), nullable=True))
    op.add_column('materials', sa.Column('is_batch_tracked', sa.Boolean(), nullable=False))
    op.add_column('materials', sa.Column('is_serialized', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'materials', 'locations', ['location_id'], ['id'])
    op.drop_column('materials', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'is_serialized')
    op.drop_column('materials', 'is_batch_tracked')
    op.drop_column('materials', 'location_id')
    op.drop_column('materials', 'reorder_level')
    op.drop_column('materials', 'reserved_stock')
    op.drop_column('materials', 'current_stock')
    # ### end Alembic commands ###
