"""Add FK constraint to materials.tenant_id

Revision ID: a1b2c3d4
Revises: 2fa_add_auth_enhancements
Create Date: 2026-04-17 10:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4'
down_revision = '2fa_add_auth_enhancements'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add FK constraint to materials.tenant_id to enforce referential integrity
    # This prevents orphaned materials if a tenant is deleted
    op.create_foreign_key(
        'fk_materials_tenant_id',
        'materials',
        'tenants',
        ['tenant_id'],
        ['id'],
        ondelete='CASCADE'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove FK constraint
    op.drop_constraint('fk_materials_tenant_id', 'materials', type_='foreignkey')
    
    # ### end Alembic commands ###
