"""Add audit trail fields (created_by, updated_by) to supplier and material models

Revision ID: a1b2c3d5
Revises: a1b2c3d4
Create Date: 2026-04-17 10:30:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d5'
down_revision = 'a1b2c3d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add audit trail columns to suppliers table
    op.add_column('suppliers', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('suppliers', sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_suppliers_created_by', 'suppliers', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_suppliers_updated_by', 'suppliers', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    
    # Add audit trail columns to materials table
    op.add_column('materials', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('materials', sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_materials_created_by', 'materials', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_materials_updated_by', 'materials', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove audit trail columns from materials table
    op.drop_constraint('fk_materials_updated_by', 'materials', type_='foreignkey')
    op.drop_constraint('fk_materials_created_by', 'materials', type_='foreignkey')
    op.drop_column('materials', 'updated_by')
    op.drop_column('materials', 'created_by')
    
    # Remove audit trail columns from suppliers table
    op.drop_constraint('fk_suppliers_updated_by', 'suppliers', type_='foreignkey')
    op.drop_constraint('fk_suppliers_created_by', 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'updated_by')
    op.drop_column('suppliers', 'created_by')
    
    # ### end Alembic commands ###
