"""Phase 2.3 Routing Models

Revision ID: bf11eecd68b9
Revises: 1d1a41830cdd
Create Date: 2026-03-25 00:03:44.014037

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf11eecd68b9'
down_revision = '1d1a41830cdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workstations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity_hours_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workstations_code'), 'workstations', ['code'], unique=True)
    op.create_index(op.f('ix_workstations_tenant_id'), 'workstations', ['tenant_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workstation_id', sa.UUID(), nullable=False),
    sa.Column('setup_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('run_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_tenant_id'), 'operations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_operations_workstation_id'), 'operations', ['workstation_id'], unique=False)
    op.create_table('bom_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bom_id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_operations_bom_id'), 'bom_operations', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_operations_operation_id'), 'bom_operations', ['operation_id'], unique=False)
    op.create_index(op.f('ix_bom_operations_tenant_id'), 'bom_operations', ['tenant_id'], unique=False)
    op.add_column('materials', sa.Column('current_cost', sa.Numeric(precision=18, scale=4), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'current_cost')
    op.drop_index(op.f('ix_bom_operations_tenant_id'), table_name='bom_operations')
    op.drop_index(op.f('ix_bom_operations_operation_id'), table_name='bom_operations')
    op.drop_index(op.f('ix_bom_operations_bom_id'), table_name='bom_operations')
    op.drop_table('bom_operations')
    op.drop_index(op.f('ix_operations_workstation_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_tenant_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_workstations_tenant_id'), table_name='workstations')
    op.drop_index(op.f('ix_workstations_code'), table_name='workstations')
    op.drop_table('workstations')
    # ### end Alembic commands ###
